@startuml
|Client|
start
:Registrasi / Login;
:Masuk ke menu Booking;
:Memilih jenis booking (portrait / wedding / keluarga);

if (Tipe: Portrait / Keluarga?) then (Ya)
  :Isi jumlah orang;
  :Pilih tanggal & jam;
else (Wedding)
  :Pilih paket wedding;
  :Pilih lokasi;
endif

:Melakukan pembayaran via Midtrans;

:Datang sesuai jadwal;
|Admin|
:Konfirmasi kehadiran client;

if (Tipe: Wedding?) then (Ya)
  :Lakukan pemotretan di lokasi;
  :Edit & finalisasi foto/video;
else
  :Pemotretan di studio;
endif

:Isi link Google Drive hasil foto;

|Client|
:Unduh hasil foto;
:Booking selesai;
stop
@enduml