@startuml
actor Client
participant Aplikasi
database Database

Client -> Aplikasi: Input email & password / daftar baru
Aplikasi -> Database: Cek / simpan user
Database --> Aplikasi: OK / Error
Aplikasi --> Client: Redirect dashboard / error
@enduml